repos:
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    language-version: python3.11
    stages: [commit]
- repo: https://github.com/pycqa/flake8
  rev: 7.0.0
  hooks:
  - id: flake8
    stages: [commit]
- repo: local
  hooks:
  - id: requirements
    name: requirements
    entry: bash -c 'venv/bin/pip3 freeze > requirements.txt; git add requirements.txt'
    language: system
    pass_filenames: false
    stages: [commit]
